Scroll Issue Solved
koustov/css-builder pull request #52
Opened 2021-10-06 08:22 UTC by donjosemathew

## Description

Fixed issue related to scrolling

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Verified that added/modified attribues are properly loading on browsing
- [ ] Verified that added/modified attribues editing templates are properly rendered
- [ ] Verified the output on changes
- [ ] Verified the deployment

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas. If applicable.
- [ ] I have made corresponding changes to the documentation. If applicable.
- [ ] My changes generate no new warnings

2021-10-06 08:24 UTC, dontech09 commented
Can You add this to Hactoberfest

2021-10-07 12:29 UTC, koustov commented
Not all scroll issues are resolved. If you add few attributes and then "Animation", notice that the height of the [viewport](url) gets extended. Please fix it.
![image](https://user-images.githubusercontent.com/7145967/136384332-3453f869-d4cd-465b-b97c-f11cc1b808d7.png)

2021-10-07 12:32 UTC, koustov requested changes

2021-10-07 12:32 UTC, koustov commented on example/src/index.css
> +  overflow-x: hidden;
overall comment added. Please see in "Conversation" tab

2021-10-07 14:51 UTC, donjosemathew commented on example/src/index.css
> +  overflow-x: hidden;
Ok I will Check that

2021-10-07 14:54 UTC, donjosemathew commented on example/src/index.css
> +  overflow-x: hidden;
I think it is working fine?

2021-10-16 04:11 UTC, koustov commented on example/src/index.css
> +  overflow-x: hidden;
it's still showing the same to me.

2021-10-16 12:20 UTC, donjosemathew commented on example/src/index.css
> +  overflow-x: hidden;
Now if the height exceeds 100vh it will show a scroll bar.I think what you are excepting is height will be 100vh always and scroll bar should be added to the child components on which content overflow?

2021-10-16 15:32 UTC, koustov commented on example/src/index.css
> +  overflow-x: hidden;
ok, accepting now however the expectation would be to enable scroll bar within the tab panel only.

2021-10-16 15:32 UTC, koustov approved these changes
lgtm

2021-10-16 15:33 UTC, merged

2021-10-16 15:34 UTC, koustov commented
@all-contributors please add @dontech09 for code